### PR TITLE
Support for 3.2

### LINKED ISSUE #172: Update OpenStack Image to support OpenShift 3.2
Update OpenStack base image to support OpenShift 3.2

### PR DESCRIPTION
**Pull request by oybed**
#### What does this PR do?

Updated the bash tools to support installing OSEv3.2. As OSE now runs dnsmasq on every node, the DNS server installed part of our tools need to be pulled out to be installed on a different host. This is now part of the "Utility" host that originally was used to install the env. This means that the Utility Host is kept around after install instead of having it automatically removed.

In addition, the current OSE v3.2 installation expects the install to be using DHCP (rather than static) for the hosts used for master and nodes. In order to use the correct DNS server, it looks for the DHCP4_DOMAIN_NAME_SERVERS parameter to populate dnsmasq correctly. To work around this, the tools now update /etc/sysconfig/network with the DNS server ip to get the correct name resolution. 
#### How should this be manually tested?

Run a provisioning, e.g.:

```
./osc-provision --num-nodes=2 --num-etcd=1 --ose-version=3.2 --key=<key>
```

Then verify that the installation was successful with 1 master + 2 nodes, in addition check that the router and registry comes up successfully. 

Bonus: Perform a build and verify that the environment works as expected and can be used to host apps.
#### Is there a relevant Issue open for this?

resolves #172 
#### Who would you like to review this?

/cc @sabre1041 @etsauer

### CODE REVIEW

**Comment by detiber** [comment]
This comment has nothing to do about this specific PR, but you can have related issues auto closed when PRs merged by adding certain keywords in front of the references in the PR description or in commit messages (fixes, resolves, etc). More info here: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by detiber** [comment]
> In addition, the current OSE v3.2 installation expects the install to be using DHCP (rather than static) for the hosts used for master and nodes. In order to use the correct DNS server, it looks for the DHCP4_DOMAIN_NAME_SERVERS parameter to populate dnsmasq correctly. To work around this, the tools now update /etc/sysconfig/network with the DNS server ip to get the correct name resolution.

The fix for this is currently undergoing QE testing and will be released in an errata release within the next couple of weeks.

**Comment by oybed** [comment]
@detiber awesome on the syntax to close out issues - will give that a try. 
Also good to hear about the change in the works for DHCP vs static. We'll watch for it and update the tools accordingly when it's ready for use.

**Comment by sabre1041** [comment]
@oybed environment created successfully and I was able to build the `cakephp-example` application

UI in 3.2 now has a lovely about page for easy validation of environment 

```
Master:
v3.2.0.20
Kubernetes Master:
v1.2.0-36-g4a3f9c5
```

**Comment by sabre1041** [comment]
@oybed one thing i did notice is that the utility host stuck around when using the command above

```
./osc-provision --num-nodes=2 --num-etcd=1 --ose-version=3.2 --key=<key>
```

Is this the expected result?

**Comment by oybed** [comment]
@sabre1041 Thanks for running through the tests. As for the Utility Host, yes, that is now the DNS server and hence has to stick around (more details in the initial comment field above). A new CLI argument has been added, `--rm-util-host`, that will allow you to remove it, if for example, a separate DNS server is being used.

**Comment by sabre1041** [comment]
@oybed serves me right before running through the installation before having my first or second cup of caffeine. thanks or the explanation! 👍 from me

**Comment by npoyant** [comment]
What is the mindset for 3.2 "expecting" DHCP instead of static? Most customers that i've seen use static for everything.

**Comment by oybed** [comment]
@npoyant agreed and that was our feedback to the OSE installer team as well. They are working a change for this (and it will most likely be ready soon, if not already).

**Comment by etsauer** [comment]
@oybed just ran through this. Looks pretty good. One thing though, you said we use the utility host as our DNS server? That's not what our final environment report shows:

```
Master:
  - Hostname: master.ose.example.com
  - IPs: 172.16.252.68|10.3.14.9
Etcd: 
Nodes: 
  - Node
  -- Hostname: master.ose.example.com
  -- IPs: 172.16.252.68|10.3.14.9
  - Node
  -- Hostname: node2.ose.example.com
  -- IPs: 172.16.252.70|10.3.14.21
  - Node
  -- Hostname: node3.ose.example.com
  -- IPs: 172.16.252.69|10.3.14.18
DNS Server: master.ose.example.com
Environment ID: testenv-sTdjUm8B
```

**Comment by oybed** [comment]
@etsauer oh no, busted :-) Yeah, I'll get the output updated with the correct one. Didn't know how long lived these tools are, so didn't want to spend too much time on them.

**Comment by etsauer** [comment]
@oybed went through some tests. everything else looks good, once the output has been changed I think we can go ahead and merge.

**Pull request merged**
