### PR TITLE
Post install playbook

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?

Various post-install related enhancements, including:
- Addition of a post-install.yaml playbook which ties in the secure-registry role and a new ssh key sync role
- Integration of post-install playbook with provision.sh script
- Minor bugfix to provision.sh script to sort inventory files by timestamp, rather than filename.
- Minor bugfix to node provisioning process to ensure that nodes use the node_storage_size var
#### How should this be manually tested?

Run provision.sh with standard parameters. Optionally, include `openshift_authorized_key_url` in your inventory, with a value being a web or file Url to a text file containing SSH Key content you'd like to sync to your instances.
#### Is there a relevant Issue open for this?

n/a
#### Who would you like to review this?

/cc @oybed @vvaldez @sabre1041 @JayKayy

### CODE REVIEW

**Comment by JayKayy** [comment]
is this PR eventually going to include logging and metrics integrations?

**Comment by etsauer** [comment]
@JayKayy depends.. are those roles ready for prime-time?

**Comment by JayKayy** [comment]
@etsauer I would say yes. Last i checked yes both roles would be coming from openshift-ansible.

**Comment by etsauer** [comment]
@JayKayy @sabre1041 @oybed would someone be able to test this?

**Comment by oybed** [comment]
@etsauer yes, I'll test this - I very much wish we had this already in the code base, so I'll put priority on testing it. BTW: I read through the changes and it looks good from the perspective  - just need to run through to test it.

**Comment by oybed** [comment]
@etsauer tested the PR and found a few things - one potentially due to other changes in `openshift-ansible` since the PR was initially opened:
- Had to add the following to the `post-install.yaml` playbook, for the `secure-registry` role  to execute successfully (possibly not the "correct" fix, but it works around an issue):

```
  vars:
    openshift_deployment_type: "{{ deployment_type }}"
```
- Need to document how to configure the environment used for execution - i.e.: setting the `roles_path` to include the `openshift-ansible` repo's roles since the `secure-registry` role depends on it.

BTW: before adding the `openshift_deployment_type` (as mentioned above), I hit the following error:

```
TASK [openshift_repos : assert] ************************************************
task path: /root/repository/openshift-ansible/roles/openshift_repos/tasks/main.yaml:10
fatal: [test1-1471562932-node1.innovation.labs.redhat.com]: FAILED! => {"failed": true, "msg": "The conditional check 'openshift_deployment_type in known_openshift_deployment_types' failed. The error was: error while evaluating conditional (openshift_deployment_type in known_openshift_deployment_types): 'openshift_deployment_type' is undefined"}
fatal: [test1-1471562932-master1.innovation.labs.redhat.com]: FAILED! => {"failed": true, "msg": "The conditional check 'openshift_deployment_type in known_openshift_deployment_types' failed. The error was: error while evaluating conditional (openshift_deployment_type in known_openshift_deployment_types): 'openshift_deployment_type' is undefined"}
```

**Comment by oybed** [comment]
Will submit follow-up PR to document the `openshift_deployment_type`

**Pull request merged**
