### PR TITLE
Fixed issue of SSH keys not being copied into container

### PR DESCRIPTION
**Pull request by sabre1041**
@JaredBurck please review

You will need to remove the existing docker image

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 I ran with:

```
./provisioning/openstack-docker-client/run.sh --keep --repository=/home/esauer/workspace/redhat-consulting/rhc-ose/ --ssh=/home/esauer/.ssh
```

and at the end, see the ssh directory twice:

```
[root@b8fe2f53df19 ~]# ls -a
.  ..  .bash_logout  .bash_profile  .bashrc  .cshrc  .openstack  .pki  .ssh  .tcshrc  anaconda-ks.cfg  repository  ssh  start.sh
```

I think we should clean that up so it only shows as the proper `.ssh`.

**Comment by etsauer** [comment]
Other than the duplicated `ssh` directory, everything seems to work.

**Comment by sabre1041** [comment]
@etsauer modified to only utilize `.ssh` folder. Would you be able to retest?

**Comment by etsauer** [comment]
Works for me

**Pull request merged**
