### PR TITLE
Added groovy and additional Jenkins plugins to CICD installation

### PR DESCRIPTION
**Pull request by sabre1041**
Added groovy and additional Jenkins plugins to CICD installation

To test and verify
- Create new cicd instance
  *\* ose3-base image
  *\* CICD security group
- Create new volume and attach to instance at /dev/vdb

Clone branch on instance and run `./provisioning/cicd-install`
- Verify groovy installed at /usr/local/groovy
- Verify additional Jenkins plugins installed
  - Groovy, Groovy Postbuild, Job DSL, Folder and supporting plugins

### CODE REVIEW

**Comment by etsauer** [comment]
[testing]

**Comment by sabre1041** [comment]
@etsauer i made a few corrections after continued testing

Issue discovered around updating "core" plugins and that they need to be [pinned](https://wiki.jenkins-ci.org/display/JENKINS/Pinned+Plugins)

Would you be able to check it out when you get the chance

**Comment by etsauer** [comment]
@sabre1041 
```
[root@ose3-new-base rhc-ose]# ./provisioning/cicd-install 
====================================
=   Installing CI/CD Environment   =
====================================

--- Validating Prerequisites ---

ERROR: Docker Volume (/dev/vdb) does not exist

=====================================================
= CICD Server Provisioning Failed!                  =
=====================================================
```

**Comment by etsauer** [comment]
@sabre1041 script ran fine. Is there anything I should do/look at to make sure the changes took affect?

**Comment by sabre1041** [comment]
@etsauer  under manage jenkins and configure system. Validate groovy is present with path specified above.

Also validate new Plugins on manage plugins page in manage jenkins

**Comment by etsauer** [comment]
looks good.

**Pull request merged**
