### PR TITLE
Inital work for dynamic SSL and DNS route updater and monitor.

### PR DESCRIPTION
**Pull request by sferich888**
@etsauer can you look at this, its a bit rough, and will likely need some TLC. It all works, except for the add certificate (patch route) the proxy throws an error, that the certificate is formatted badly.

### CODE REVIEW

**Comment by etsauer** [comment]
cc: @oybed @sabre1041 @timothyh

**Comment by etsauer** [comment]
So here's my opinion on how we move this forward.

MVP (1st merge):
- pull the environment specific stuff out of this script and into either a separate config file, environment variables, or script args
- create a README describing how to setup and run it.

Future State:
- Dockerize the script (centos and rhel flavors)
- Refactor the script into:
  - a generic watcher script skeleton
  - a "plugin" implementation specific to Routes/IPA
- enhance README to document use cases

**Comment by etsauer** [comment]
@sferich888 do you want to handle the first set of items or should one of us take this over?

**Comment by woot4moo** [comment]
We should not hard code 2048 as the bit count and we should go a step further by requiring a **strong** password on PEM creation.

**Comment by sferich888** [comment]
Feel free to take over I will contribute where I can.

**Comment by etsauer** [comment]
This has been moved out to its own repo: https://github.com/rhtconsulting/ocp-watcher-skel

Closing

**Comment by oybed** [comment]
Closing per above comment

**Pull request closed without merging**
