### PR TITLE
Add enhancements for for terminate playbook

### PR DESCRIPTION
**Pull request by vvaldez**
#### What does this PR do?

The following use cases were identified during testing of PR #196 and submitted separately here.
- Add check for valid item when attempting to delete objects
- Add debug on all variables when using dry_run
- Changed default ansible_ssh_user to cloud-user in line with standard cloud guest image
- Add count for ips and volumes to display since these may not always be the same as instance count
- Enhance displayed warning/note message to include new counts
- It is possible for an instance to not have a floating IP for whatever reason (such as manually de-allocating or releasing the IP), in this case SSH will not work to the instance so it will not be included in the host group to attempt subscription manager unregister, but will still be deleted
- It is possible that an instance will have a volume created but not attached. In this case as a precautionary measure I am excluding these unattached volumes from the deletion in case this was intentionally detached to preserve data. We can further discuss if this should be a parameter to override instead or if we need to change this behavior.
- Excluded instances in ERROR state as they will most likely not delete. We can discuss if this should be parameterized instead.
#### How should this be manually tested?

Call terminate.yml as normal and if desired manually introduce the following scenarios:
- Manually detach a volume from an instance in the env_id that is passed to the playbook
- Manually deallocate or delete/release a floating IP attached to an instnace in the env_id that is passed to the playbook
- Attempt to delete an instance that is in ERROR state in the env_id that is passed to the playbook
- Use the -e "dry_run=true" parameter and view the debug output of all variables
#### Is there a relevant Issue open for this?

None, though optionally the **ansible_ssh_user** can be omitted and the user would need to specify this outside the playbook. I changed this to **cloud-user** as it is the most commonly used user for the cloud guest image.
#### Who would you like to review this?

/cc @oybed @etsauer @sabre1041

### CODE REVIEW

**Comment by etsauer** [comment]
@vvaldez first off, since we merged your other terminate enhacement, this PR needs updating.

Second, I tried running on a set of instances that are "unreachable" in the subscription-manager task. the terminate failed and the instances are still around.

**Comment by vvaldez** [comment]
@etsauer can you post the result of **nova list** for these instances or are they still around? How can I replicate this unreachable state or do you have the playbook run result?

**Comment by etsauer** [comment]
@vvaldez you can re-create the issue by passing an incorrect value for ansible_ssh_user to the playbook

**Comment by vvaldez** [comment]
The issue was two fold here. First the grep was improperly capturing a **|** when the Floating IP didn't exist. Secondly, since this was used in the host group the subscription-manager task failed since it obviously can't reach a host with that name. This can also occur as noted in Issue #206 when the instance can't be reached. Addressed these issues in the latest commit by fixing the grep and also added **prompt** (at @etsauer request) and **unregister** variables set to **true** by default but can be overridden. In case an instance should not attempt to unregister this can be set to false to bypass this task.

**Comment by etsauer** [comment]
lgtm

**Pull request merged**
