### PR TITLE
Added full list of dependencies required for workflow plugin

### PR DESCRIPTION
**Pull request by sabre1041**
#### What does this PR do?

Adds the full list of Jenkins plugin dependencies for the workflow plugin to the CICD server
#### How should this be manually tested?

Provision new CICD environment and validate these plugins are visible in the installed plugins page
#### Is there a relevant Issue open for this?

None
#### Who would you like to review this?

/cc @JaredBurck

### CODE REVIEW

**Comment by JaredBurck** [comment]
Although the Jenkins plugin dependencies for the workflow plugin do get installed, the build is still unstable.

```
channel stopped
Processing DSL script DslEnvironmentGenerator.groovy
Warning: (OseWorkflowJob.groovy, line 67) plugin 'workflow-aggregator' needs to be installed
Added items:
    GeneratedJob{name='ticket-monster-workflow'}
Build step 'Process Job DSLs' changed build result to UNSTABLE
Finished: UNSTABLE
```

The workflow plugin has been renamed to pipeline. See https://issues.jenkins-ci.org/browse/JENKINS-31153 for more information. And after additional investigations and work with @sabre1041 there were additional missing dependencies.

**Comment by sabre1041** [comment]
@JaredBurck I have added the additional plugins that were preventing the proper installation of the workflow plugin. Would you be able to retest?

**Comment by JaredBurck** [comment]
Provisioned new CICD environment and validated that all missing and required Jenkins plugins have been installed and are visible in the plugins page.  This PR can now be merged.

**Comment by sabre1041** [comment]
@esauer @oybed can you please merge this as @JaredBurck has signed off?

**Pull request merged**
