### PR TITLE
Provision cicd

### PR DESCRIPTION
**Pull request by etsauer**
To test:
1. Make the following change in `./provisioning/sample.cfg`:
   `CONF_PROVISION_COMPONENTS=openshift`
   becomes
   `CONF_PROVISION_COMPONENTS=cicd`
2. Run the provisioning script

```
$ ./provisioning/osc-provision --key=<keyname> --config=./provisioning/sample.cfg
Provisioning CICD Server. This could take several minutes.
Complete!
...
CICD Server: 172.16.166.38|10.3.8.107
Environment ID: n81HZoOA
```
1. Once validation is complete, delete the environment:
   `./provisioning/osc-provision --delete=<Environment ID>`

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer  Having some trouble running the script

```
./osc-provision --key=ablock-osx
Missing argument: --num-nodes <integer>
```

**Comment by etsauer** [comment]
@sabre1041 sorry.. missed an argument. fixed now

**Comment by sabre1041** [comment]
@etsauer did you push the change?

**Comment by etsauer** [comment]
@sabre1041 there was no change.. just updated the testing instructions above to add the `--config=` flag.

**Comment by sabre1041** [comment]
@esauer provision successful

Should we add the CICD provision to the documentation?

**Comment by sabre1041** [comment]
looks good

**Pull request merged**
