### PR TITLE
Subscription manager register and create security groups as needed

### PR DESCRIPTION
**Pull request by vvaldez**

### CODE REVIEW

**Comment by oybed** [comment]
@vvaldez As discussed on the call, please re-factor to split into various roles (i.e.: the subscription-manager in its own, etc.) + rename "RHN" to maybe "RHCP" (Red Hat Customer Portal), or maybe something related to "subscription manager" - https://access.redhat.com/articles/63269

**Comment by vvaldez** [comment]
Renamed "rhn" to "rhsm" for brevity and clarity. Will work on re-factoring.

**Comment by vvaldez** [comment]
Refactored into a separate role for subscription-manager and added a README to describe the parameters. Added support for Satellite and tested. Also added a way to disable subscription management completely (the default).

**Comment by vvaldez** [comment]
I've split this into three PRs to manage each feature and closing this PR.
1. #133 Add subscription-manager support for Hosted or Satellite
2. #134 Add OpenStack SSH key parameter check
3. #135 Add OpenStack security group detection and creation

**Pull request closed without merging**
