### PR TITLE
Role info

### PR DESCRIPTION
**Pull request by JayKayy**
#### What does this PR do?

Adds blank README for listing required and optional variables for the roles. The intention is that people who authored roles will comment with variable requirements.
#### How should this be manually tested?

N/A
#### Is there a relevant Issue open for this?

N/A
#### Who would you like to review this?

/cc @etsauer  @sabre1041 @oybed And anyone who authored a role in this repo

### CODE REVIEW

**Comment by oybed** [comment]
Like the approach on getting better documentation in place. Some of these, roles, however, will not be OSE3 specific and should be kept generic. Hence probably would want to not enforce that the variables are added to the [OSEv3:vars] section.

**Comment by JayKayy** [comment]
@oybed Changed the README.

**Comment by oybed** [comment]
I'm good with it. @etsauer & @sabre1041 any additional comments?

**Comment by sabre1041** [comment]
@JayKayy @oybed good on my end

**Pull request merged**
