### PR TITLE
Full install

### PR DESCRIPTION
**Pull request by JayKayy**
#### What does this PR do?

This is the early attempts at stringing together the other CASL roles to automate an OSE installation on Openstack.
#### How should this be manually tested?

Configure the inventory file similar to  rhc-ose-ansible/inventory/ose-provision and make sure you fill out your rhn username and password fields, as well as a valid subscription manager pool_id.

Spin up the development environment image.
`rhc-ose/docker/openstack-docker-client/run.sh --repository=<rhc-ose>`

Run the ose-provision.yml playbook
`ansible-playbook -i inventory_file rhc-ose/rhc-ose-ansible/ose-provision.yml`
#### Is there a relevant Issue open for this?

N/A
#### Who would you like to review this?

/cc @oybed  @etsauer @sabre1041

### CODE REVIEW

**Comment by etsauer** [comment]
@JayKayy i'm getting an error immediately trying to run this:

```
[root@e5b19d3d14fe rhc-ose-ansible]# ansible-playbook -i inventory/ose-provision ose-provision.yml
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR: file could not read: /tmp/records.yaml
[root@e5b19d3d14fe rhc-ose-ansible]# 
```

**Comment by oybed** [comment]
@etsauer @JayKayy I was able to successfully run through the provisioning more than once. Maybe we should compare the inventory file to see if there's something obvious there? ... or do you have any other ideas for how to proceed?

**Comment by JayKayy** [comment]
Unfortunately this started popping up for me as well early yesterday. im looking for how to solve it. It seems ansible is checking the includes before even beginning the play. This error is occuring because records.yaml is a task file that is generated at runtime and filled out based on our hosts and ip addresses/namespaces etc. I'm working on a workaround now

**Comment by JayKayy** [comment]
Should be fixed now.

**Comment by etsauer** [comment]
Closing this, carrying on the work in https://github.com/rhtconsulting/rhc-ose/pull/168

**Pull request closed without merging**
