### PR TITLE
Add OpenStack terminate

### PR DESCRIPTION
**Pull request by vvaldez**
#### What does this PR do?

This PR adds a playbook that relies on your sourced OpenStack credentials to get a list of nova instances matching a supplied **env_id**, then unregister from subscripiton-manager, delete these instances, then delete any attached volumes. This is useful when provisioning and tearing down environments using the provisioning playbooks.

Currently this uses environment variables to list instances. Only the instances matching the supplied string will be deleted, so this has been safely tested to not damage any non-matching instances. However, as with any string matching, this should be as specific and unique as possible. An 'env_id' of "testenv" will also match "testenv1" and "testenv2" and so on. 
#### How should this be manually tested?

To test this first source your openrc.sh file, provision an environment with a unique 'env_id', optionally list instances and volumes (to verify after), then run the playbook. Verify that everything was cleaned up after.

```
source ~/.openstack/openrc.sh
nova list
nova volume-list
ansible-playbook openstack-deprovision.yml -e 'env_id=testenvX'
nova list
nova volume-list
```

Additional items that can be tested:
- No successful connection to environment should halt with an error
- No specified **env_id** should fail
- **env_id** length of less than 8 should fail
- More than 6 matching instances should fail
- Overriding the above should succeed either by individual variable override or via **really_really_sure=true** parameter
- Override with no specified **env_id** should match all instances
- 'dry_run' shows what would be deleted, this works well as the actual tasks will be skipped by show the IDs that would be deleted when set to true
- Debug info is available for the custom host group if **dry_run=true** is set
- If images used in matching instances are not unique, a warning will prompt. The reason is that if a different **ansible_ssh_user** is needed for the different users, then the subscription-manager task might fail on instances with different users
#### Is there a relevant Issue open for this?

No current issues.
#### Who would you like to review this?

/cc @oybed @sabre1041 @etsauer

### CODE REVIEW

**Comment by oybed** [comment]
Including @etsauer and @sabre1041 for review as well.

**Comment by oybed** [comment]
@vvaldez Considering the environments we're operating in, and shared tentants among users, we cannot submit/merge this PR as-is. We need to limit what it does by default - i.e.: a filter is required so it only deletes what's related to that filter - and preferably even more limiting - i.e; only allow removal of environments that we know are safe to remove. We have had some experiences in the past where people have removed too much, and we'd want to ensure our tools are safe and doesn't pose such a risk. :-)

**Comment by vvaldez** [comment]
Added filtering based on a specified 'env_id' variable. I also added a pause to confirm before proceeding.

**Comment by vvaldez** [comment]
I've updated the PR description to reflect the new commit.

**Comment by vvaldez** [comment]
Refactored role to remove dynamic inventory and add features from previous bash script.

**Comment by vvaldez** [comment]
Implemented changes discussed and moved playbook into the playbooks directory.

**Comment by vvaldez** [comment]
Added **ansible_sudo: true** when calling the subscription-manager task. 

One possible issue with this PR that should be noted is if using different images for various instances, only one **ansible_ssh_user** can be specified since the inventory is dynamically created and thus any instances using a different user will fail the subscription-manager task. Failure is ignored so this playbook will continue, but those subscription will remain consumed. To avoid this issue, only delete environments in batch that use the same image. We could possibly add a check if instances use a different image and warn the user.

**Comment by etsauer** [comment]
@vvaldez i don't think a check is necessary at this point. If it's an issue we start to see we can address it then, but for now, we're not really using multiple images in a single cluster.

**Comment by etsauer** [comment]
@vvaldez in keeping with other naming schemes i see in cloud provider stuff, I'm thinking maybe a rename to terminate.yml?

**Comment by vvaldez** [comment]
@etsauer I had already worked on adding image detection. It wasn't so much for multiple images within one cluster, but having multiple clusters up each with different images and wanting to terminate in batches. The latest commit adds this logic.

**Comment by vvaldez** [comment]
Demo showing various scenarios in an environment with multiple clusters: https://youtu.be/XEjvWuoFzdg

**Comment by etsauer** [comment]
@vvaldez FINALLY tested this. everything looks great! I'm going to merge.

**Pull request merged**
