### PR TITLE
Updated permissions for registry mount in 3.1.1

### PR DESCRIPTION
**Pull request by sabre1041**
#### What does this PR do?

Updated permissions for registry mount in 3.1.1 based on solution recommendations 

https://access.redhat.com/solutions/2173071
#### How should this be manually tested?
1. Provision new OSE environment
2. Create a new project
3. Deploy **cakephp-example** instant application
4. Verify build completes and pushes successfully to integrated registry
#### Is there a relevant Issue open for this?

No
#### Who would you like to review this?

/cc @oybed @etsauer

### CODE REVIEW

**Comment by oybed** [comment]
@sabre1041 looks good. Please let me know if you'd like me to merge.

**Comment by sabre1041** [comment]
Its good with me. @etsauer do you want to take a look

**Comment by etsauer** [comment]
@sabre1041 if you guys are good, i'm good.

**Comment by sabre1041** [comment]
@etsauer @oybed merge away!

**Pull request merged**
